create table if not exists public.open_me_pledges (
  id bigint generated by default as identity primary key,
  first_name text not null,
  zip_code text not null,
  commitment boolean not null default true,
  source text,
  created_at timestamptz not null default now()
);

create index if not exists open_me_pledges_created_at_idx
  on public.open_me_pledges (created_at desc);

alter table public.open_me_pledges enable row level security;

drop policy if exists "open_me_pledges_anon_insert" on public.open_me_pledges;
create policy "open_me_pledges_anon_insert"
  on public.open_me_pledges
  for insert
  to anon
  with check (true);

drop policy if exists "open_me_pledges_anon_select" on public.open_me_pledges;
create policy "open_me_pledges_anon_select"
  on public.open_me_pledges
  for select
  to anon
  using (true);
